### PR TITLE
fix: data already downloaded

### PR DESCRIPTION
**Pull request by jasperzhong**

### CODE REVIEW

**Comment by akhatua2** [comment]
Hi Jasper, thank you very much for adding this check. For modularity could you please move this check into the existing `decide_download` function. Otherwise LGTM!

**Comment by akhatua2** [comment]
Hi Jasper, thank you very much for adding this check. For modularity could you please move this check into the existing `decide_download` function. Otherwise LGTM!

**Review by akhatua2 — CHANGES_REQUESTED** [review]
Hi Jasper, thank you very much for adding this check. For modularity could you please move this check into the existing `decide_download` function. Otherwise LGTM!

**Comment by msharmavikram** [comment]
@akhatua2 if this can be merged, it would be great!

**Review by akhatua2 — APPROVED** [review]

**Pull request merged**
